version: "2"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
        - VERCEL_API_KEY=<API_KEY_HERE>
        - DOMAIN=<DOMAIN_HERE>
        - SUBDOMAIN=<SUBDOMAIN_HERE>